<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { ElMessage } from 'element-plus'
import { getAdminAnnouncements, saveAnnouncement, type Announcement } from '../../api/admin'

const loading = ref(false); const saving = ref(false); const items = ref<Announcement[]>([])
const form = reactive<{ id?: number; title: string; content: string; status: string }>({ title: '', content: '', status: 'published' })
async function load() { loading.value = true; try { items.value = (await getAdminAnnouncements()).data || [] } catch (error) { ElMessage.error(error instanceof Error ? error.message : '公告加载失败') } finally { loading.value = false } }
function edit(item: Announcement) { Object.assign(form, { id: item.id, title: item.title, content: item.content, status: item.status }) }
function clear() { Object.assign(form, { id: undefined, title: '', content: '', status: 'published' }) }
async function save() { if (!form.title.trim() || !form.content.trim()) { ElMessage.warning('请填写公告标题和内容'); return }; saving.value = true; try { await saveAnnouncement(form); ElMessage.success('公告已保存'); clear(); await load() } catch (error) { ElMessage.error(error instanceof Error ? error.message : '公告保存失败') } finally { saving.value = false } }
onMounted(load)
</script>
<template><div class="page-heading"><div><h1>公告管理</h1></div></div><el-row :gutter="16"><el-col :xs="24" :md="10"><el-card><template #header>{{ form.id ? '编辑公告' : '发布公告' }}</template><el-form label-position="top"><el-form-item label="标题"><el-input v-model="form.title" maxlength="80" :disabled="form.status === 'archived'" /></el-form-item><el-form-item label="内容"><el-input v-model="form.content" type="textarea" :rows="9" maxlength="5000" show-word-limit :disabled="form.status === 'archived'" /></el-form-item><el-form-item label="状态"><el-radio-group v-model="form.status" :disabled="form.status === 'archived'"><el-radio-button label="published">发布</el-radio-button><el-radio-button label="archived">归档</el-radio-button></el-radio-group></el-form-item><el-button v-if="form.status !== 'archived'" type="primary" :loading="saving" @click="save">{{ form.id ? '保存修改' : '发布公告' }}</el-button><el-button v-if="form.id" @click="clear">取消编辑</el-button></el-form></el-card></el-col><el-col :xs="24" :md="14"><el-card v-loading="loading"><template #header>公告列表</template><el-empty v-if="!items.length" description="暂无公告" /><div v-for="item in items" :key="item.id" class="announcement-admin-item"><div class="announcement-admin-head"><strong>{{ item.title }}</strong><el-tag :type="item.status === 'published' ? 'success' : 'info'">{{ item.status === 'published' ? '已发布' : '已归档' }}</el-tag></div><p class="announcement-content">{{ item.content }}</p><el-button v-if="item.status === 'published'" link type="primary" @click="edit(item)">编辑</el-button><el-button v-if="item.status === 'published'" link type="warning" @click="Object.assign(form, { id: item.id, title: item.title, content: item.content, status: 'archived' }); save()">归档</el-button><span v-else class="form-help">已归档，禁止修改</span></div></el-card></el-col></el-row></template>
