<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { ElMessage } from 'element-plus'
import { getAuditLogs, type AuditLog } from '../../api/admin'
import { formatDateTime } from '../../utils/format'
const loading = ref(false); const logs = ref<AuditLog[]>([]); const total = ref(0); const page = ref(1)
const actionNames: Record<string, string> = { 'user.status.update': '修改用户状态', 'user.role.update': '修改用户角色', 'settings.registration.update': '修改注册设置', 'settings.update': '修改系统设置', 'wallet.transfer': '用户转账', 'wallet.adjustment': '管理员调整金币' }
const resourceNames: Record<string, string> = { user: '用户', system_settings: '系统设置', wallet: '钱包' }
function actionName(value: string) { return actionNames[value] || '管理员操作' }
function resourceName(value: string) { return resourceNames[value] || value }
function detailText(log: AuditLog) { try { const detail = JSON.parse(log.details) as Record<string, unknown>; if (log.action === 'wallet.transfer') return `${detail.sender || '转账人'} 给 ${detail.recipient || '收款人'} 转账 ${detail.amount} 金币，转账前余额 ${detail.balance_before}，转账后余额 ${detail.balance_after}`; if (log.action === 'wallet.adjustment') return `${detail.description || '管理员操作'}，调整 ${detail.amount} 金币，调整后余额 ${detail.balance_after}`; if (log.action === 'settings.registration.update' || log.action === 'settings.update') return `系统名称：${detail.system_name || '-'}，注册功能${detail.registration_enabled ? '已开启' : '已关闭'}，新用户赠送 ${detail.register_gift_coins ?? 0} 金币`; if (detail.from !== undefined && detail.to !== undefined) return `从“${detail.from === 'active' ? '正常' : detail.from === 'disabled' ? '禁用' : detail.from === 'admin' ? '管理员' : '普通用户'}”调整为“${detail.to === 'active' ? '正常' : detail.to === 'disabled' ? '禁用' : detail.to === 'admin' ? '管理员' : '普通用户'}”`; return '已完成操作' } catch { return '已完成操作' } }
async function load() { loading.value = true; try { const result = await getAuditLogs(page.value, 20); logs.value = result.data?.items || []; total.value = result.data?.total || 0 } catch (error) { ElMessage.error(error instanceof Error ? error.message : '审计日志加载失败') } finally { loading.value = false } }
onMounted(load)
</script>

<template><div class="page-heading"><div><h1>操作记录</h1></div></div><el-card><el-table v-loading="loading" :data="logs" empty-text="暂无操作记录"><el-table-column prop="admin_username" label="操作人" width="140" /><el-table-column label="操作内容" min-width="220"><template #default="scope">{{ scope.row.action === 'wallet.transfer' ? `${JSON.parse(scope.row.details).sender || '用户'} 给 ${JSON.parse(scope.row.details).recipient || '用户'} 转账 ${JSON.parse(scope.row.details).amount} 金币` : actionName(scope.row.action) }}</template></el-table-column><el-table-column label="操作对象" width="150"><template #default="scope">{{ scope.row.action === 'wallet.transfer' ? `用户 #${scope.row.resource_id}` : `${resourceName(scope.row.resource_type)} ${scope.row.resource_id ? `#${scope.row.resource_id}` : ''}` }}</template></el-table-column><el-table-column label="详细说明" min-width="300"><template #default="scope"><el-tooltip :content="detailText(scope.row)" placement="top-start"><span class="audit-detail">{{ detailText(scope.row) }}</span></el-tooltip></template></el-table-column><el-table-column label="操作时间" min-width="180"><template #default="scope">{{ formatDateTime(scope.row.created_at) }}</template></el-table-column></el-table><div class="table-pagination"><el-pagination v-model:current-page="page" background layout="prev, pager, next" :page-size="20" :total="total" @current-change="load" /></div></el-card></template>
