<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { getUsers, resetUserPassword, updateUserRole, updateUserStatus, type AdminUser } from '../../api/admin'
import { formatDateTime } from '../../utils/format'
import { adjustWallet } from '../../api/wallet'
const loading = ref(false); const total = ref(0); const page = ref(1); const users = ref<AdminUser[]>([])
const filters = reactive({ keyword: '', status: '', role: '' })
const walletDialog = ref(false); const walletSaving = ref(false); const selectedUser = ref<AdminUser | null>(null); const walletForm = reactive({ amount: 0, description: '' })
function openWallet(user: AdminUser) { selectedUser.value = user; walletForm.amount = 0; walletForm.description = ''; walletDialog.value = true }
async function saveWallet() { if (!selectedUser.value || !Number.isInteger(walletForm.amount) || walletForm.amount === 0) { ElMessage.warning('请输入非零整数金币数量'); return }; walletSaving.value = true; try { await adjustWallet(selectedUser.value.id, walletForm.amount, walletForm.description.trim() || '管理员操作'); ElMessage.success('金币调整成功'); walletDialog.value = false; await load() } catch (error) { ElMessage.error(error instanceof Error ? error.message : '金币调整失败') } finally { walletSaving.value = false } }
async function load() { loading.value = true; users.value = []; try { const result = await getUsers({ page: page.value, page_size: 20, ...filters }); users.value = result.data?.items || []; total.value = result.data?.total || 0 } catch (error) { total.value = 0; ElMessage.error(error instanceof Error ? error.message : '用户加载失败') } finally { loading.value = false } }
async function changeStatus(user: AdminUser) { const next = user.status === 'active' ? 'disabled' : 'active'; try { await ElMessageBox.confirm(`确认将用户“${user.username}”${next === 'active' ? '启用' : '禁用'}？`, '操作确认'); await updateUserStatus(user.id, next); ElMessage.success('用户状态已更新'); await load() } catch (error) { if (error !== 'cancel') ElMessage.error(error instanceof Error ? error.message : '操作失败') } }
async function changeRole(user: AdminUser) { const next = user.role === 'admin' ? 'user' : 'admin'; try { await ElMessageBox.confirm(`确认将用户“${user.username}”${next === 'admin' ? '设为管理员' : '降级为普通用户'}？`, '操作确认'); await updateUserRole(user.id, next); ElMessage.success('用户角色已更新'); await load() } catch (error) { if (error !== 'cancel') ElMessage.error(error instanceof Error ? error.message : '操作失败') } }
async function resetPassword(user: AdminUser) { try { await ElMessageBox.confirm(`确认重置用户“${user.username}”的密码？该用户的所有登录会话将失效。`, '重置密码'); const result = await resetUserPassword(user.id); await ElMessageBox.alert(`<div class="generated-password"><p>用户：${result.data?.username || user.username}</p><strong>${result.data?.password || ''}</strong><p>请复制并安全转交给用户，关闭后将无法再次查看。</p></div>`, '新密码', { dangerouslyUseHTMLString: true, confirmButtonText: '知道了' }); } catch (error) { if (error !== 'cancel') ElMessage.error(error instanceof Error ? error.message : '密码重置失败') } }
onMounted(load)
</script>

<template><div class="page-heading"><div><h1>用户管理</h1></div></div><el-card><el-form inline @submit.prevent="page = 1; load()"><el-form-item><el-input v-model="filters.keyword" placeholder="搜索用户名" clearable /></el-form-item><el-form-item><el-select v-model="filters.status" placeholder="用户状态" clearable><el-option label="正常" value="active" /><el-option label="已禁用" value="disabled" /></el-select></el-form-item><el-form-item><el-select v-model="filters.role" placeholder="用户角色" clearable><el-option label="普通用户" value="user" /><el-option label="管理员" value="admin" /></el-select></el-form-item><el-form-item><el-button type="primary" @click="page = 1; load()">查询</el-button></el-form-item></el-form><el-table v-loading="loading" :data="users" empty-text="暂无用户"><el-table-column prop="id" label="ID" width="80" /><el-table-column prop="username" label="用户名" min-width="160" /><el-table-column prop="coins" label="金币余额" width="110" /><el-table-column label="角色" width="120"><template #default="scope"><el-tag :type="scope.row.role === 'admin' ? 'warning' : 'info'">{{ scope.row.role === 'admin' ? '管理员' : '普通用户' }}</el-tag></template></el-table-column><el-table-column label="状态" width="100"><template #default="scope"><el-tag :type="scope.row.status === 'active' ? 'success' : 'danger'">{{ scope.row.status === 'active' ? '正常' : '禁用' }}</el-tag></template></el-table-column><el-table-column label="注册时间" min-width="180"><template #default="scope">{{ formatDateTime(scope.row.created_at) }}</template></el-table-column><el-table-column label="操作" fixed="right" width="370"><template #default="scope"><el-button link type="primary" @click="openWallet(scope.row)">调整金币</el-button><el-button link type="primary" @click="changeStatus(scope.row)">{{ scope.row.status === 'active' ? '禁用' : '启用' }}</el-button><el-button link type="warning" @click="changeRole(scope.row)">{{ scope.row.role === 'admin' ? '降级' : '设为管理员' }}</el-button><el-button link type="danger" @click="resetPassword(scope.row)">重置密码</el-button></template></el-table-column></el-table><div class="table-pagination"><el-pagination v-model:current-page="page" background layout="prev, pager, next" :page-size="20" :total="total" @current-change="load" /></div></el-card><el-dialog v-model="walletDialog" title="调整用户金币" width="420px"><p>用户：{{ selectedUser?.username }}，当前余额：{{ selectedUser?.coins ?? 0 }}</p><el-form label-position="top"><el-form-item label="调整数量"><el-input-number v-model="walletForm.amount" :step="1" step-strictly controls-position="right" /></el-form-item><el-form-item label="原因（选填）"><el-input v-model="walletForm.description" maxlength="100" placeholder="为空则记录为管理员操作" /></el-form-item></el-form><template #footer><el-button @click="walletDialog = false">取消</el-button><el-button type="primary" :loading="walletSaving" @click="saveWallet">确认调整</el-button></template></el-dialog></template>
