<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { ElMessage } from 'element-plus'
import { getTransactions, getWallet, redeemCode, transferCoins, type Wallet, type WalletTransaction } from '../../api/wallet'
import { useAuthStore } from '../../stores/auth'
import { ElMessageBox } from 'element-plus'
import { formatDateTime } from '../../utils/format'
const loading = ref(true); const redeeming = ref(false); const wallet = ref<Wallet | null>(null); const transactions = ref<WalletTransaction[]>([]); const total = ref(0); const page = ref(1); const code = ref('')
const names: Record<string, string> = { register_gift: '注册赠送', admin_adjustment: '管理员调整', redeem_code: '卡密兑换', transfer_out: '转账转出', transfer_in: '转账转入' }
const auth = useAuthStore(); const transferSaving = ref(false); const transfer = ref({ recipient_id: 0, recipient_name: '', amount: 1 })
async function sendTransfer() { if (!transfer.value.recipient_id || !transfer.value.recipient_name.trim() || transfer.value.amount < 1 || transfer.value.recipient_id === auth.user?.id) { ElMessage.warning('请输入正确的收款信息，且不能给自己转账'); return }; try { await ElMessageBox.confirm('转账立即生效，无法撤回！请确认收款用户 ID、用户名和金额均正确。', '确认转账', { type: 'warning' }); transferSaving.value = true; await transferCoins(transfer.value.recipient_id, transfer.value.recipient_name.trim(), transfer.value.amount); ElMessage.success('转账成功，已立即生效且无法撤回'); transfer.value = { recipient_id: 0, recipient_name: '', amount: 1 }; await load() } catch (error) { if (error !== 'cancel') ElMessage.error(error instanceof Error ? error.message : '转账失败') } finally { transferSaving.value = false } }
async function load() { loading.value = true; try { const [walletResult, transactionResult] = await Promise.all([getWallet(), getTransactions(page.value)]); wallet.value = walletResult.data; transactions.value = transactionResult.data?.items || []; total.value = transactionResult.data?.total || 0 } catch (error) { ElMessage.error(error instanceof Error ? error.message : '钱包加载失败') } finally { loading.value = false } }
async function redeem() { if (!code.value.trim()) { ElMessage.warning('请输入卡密'); return }; redeeming.value = true; try { const result = await redeemCode(code.value); ElMessage.success(`兑换成功，获得 ${result.data?.amount || 0} 金币`); code.value = ''; await load() } catch (error) { ElMessage.error(error instanceof Error ? error.message : '兑换失败') } finally { redeeming.value = false } }
onMounted(load)
</script>
<template><div class="page-heading"><div><h1>我的钱包</h1></div></div><el-row :gutter="14" class="wallet-top-row equal-row"><el-col :xs="24" :md="7"><el-card v-loading="loading" class="wallet-balance"><template #header>钱包余额</template><div class="overview-label">当前金币</div><div class="wallet-coins">{{ wallet?.coins ?? 0 }}</div><div class="form-help">更新时间：{{ formatDateTime(wallet?.updated_at) }}</div></el-card></el-col><el-col :xs="24" :md="17"><el-card class="redeem-card"><template #header>兑换卡密</template><el-form class="redeem-form" inline @submit.prevent="redeem"><el-input v-model="code" maxlength="30" placeholder="请输入卡密" clearable /><el-button type="primary" :loading="redeeming" native-type="submit">立即兑换</el-button></el-form></el-card></el-col></el-row><el-card class="transfer-card"><template #header>用户转账</template><el-form inline class="transfer-form" @submit.prevent="sendTransfer"><el-form-item label="收款 ID"><el-input-number v-model="transfer.recipient_id" :min="1" controls-position="right" /></el-form-item><el-form-item label="收款用户名"><el-input v-model="transfer.recipient_name" /></el-form-item><el-form-item label="金币数量"><el-input-number v-model="transfer.amount" :min="1" :step="1" controls-position="right" /></el-form-item><el-button type="primary" :loading="transferSaving" native-type="submit">确认转账</el-button></el-form><div class="form-help">转账立即生效，无法撤回；系统会同时核对收款用户 ID 和用户名。</div></el-card><el-card class="wallet-transactions"><template #header>金币流水</template><el-table :data="transactions" empty-text="暂无金币流水"><el-table-column label="类型" width="160"><template #default="scope">{{ names[scope.row.transaction_type] || '金币变动' }}</template></el-table-column><el-table-column label="变动数量" width="130"><template #default="scope"><span :class="scope.row.amount > 0 ? 'coin-positive' : 'coin-negative'">{{ scope.row.amount > 0 ? '+' : '' }}{{ scope.row.amount }}</span></template></el-table-column><el-table-column prop="balance_after" label="变动后余额" width="140" /><el-table-column prop="description" label="说明" min-width="220" /><el-table-column label="时间" min-width="180"><template #default="scope">{{ formatDateTime(scope.row.created_at) }}</template></el-table-column></el-table><div class="table-pagination"><el-pagination v-model:current-page="page" background layout="prev, pager, next" :page-size="20" :total="total" @current-change="load" /></div></el-card></template>
